// // // // app/api/ai/interpret-gradcam/route.ts
// // // import { NextRequest, NextResponse } from "next/server";
// // // import Anthropic from "@anthropic-ai/sdk";

// // // const client = new Anthropic();

// // // export async function POST(req: NextRequest) {
// // //   try {
// // //     const body = await req.json();
// // //     const {
// // //       gradcamBase64,   // base64 تاع صورة الـ Grad-CAM
// // //       detections,      // [{ label, confidence, severity, location }]
// // //       analysisType,    // "detection" | "segmentation"
// // //       overallRisk,     // "normal" | "moderate" | "high"
// // //       modelVersion,    // "ViT Hybrid" etc
// // //     } = body;

// // //     if (!gradcamBase64) {
// // //       return NextResponse.json({ error: "No Grad-CAM image provided" }, { status: 400 });
// // //     }

// // //     // نبني الـ prompt الطبي
// // //     const findingsSummary = detections?.length > 0
// // //       ? detections.map((d: any) =>
// // //           `- ${d.label} (Confidence: ${Math.round(d.confidence)}%, Severity: ${d.severity}, Location: ${d.location || "unspecified"})`
// // //         ).join("\n")
// // //       : "No pathological findings detected.";

// // //     const systemPrompt = `You are an expert gastroenterologist and medical AI specialist. 
// // // You are analyzing a Gradient-weighted Class Activation Map (Grad-CAM) heatmap generated by an AI model (${modelVersion}) during endoscopic image analysis.
// // // Your role is to provide a professional, concise radiological interpretation of the activation map for inclusion in a formal medical report.
// // // Write in clear, formal medical language suitable for a gastroenterology report.
// // // Be specific about anatomical regions, activation patterns, and clinical significance.
// // // Do NOT mention that this is AI-generated text. Write as a physician would write in a compte rendu.`;

// // //     const userPrompt = `Analysis Context:
// // // - Analysis type: ${analysisType === "detection" ? "Lesion Detection (Computer-Aided Detection)" : "Lesion Segmentation (Pixel-level Analysis)"}
// // // - Overall risk assessment: ${overallRisk}
// // // - AI Model: ${modelVersion}
// // // - Detected findings:
// // // ${findingsSummary}

// // // The attached image is the Grad-CAM activation heatmap overlaid on the endoscopic image.
// // // Hot regions (red/yellow) indicate areas of highest neural network attention during the classification decision.
// // // Cold regions (blue/purple) indicate areas of low diagnostic relevance.

// // // Please provide a structured medical interpretation with these sections:
// // // 1. **Activation Pattern** (2-3 sentences): Describe the spatial distribution and intensity of activation zones observed in the heatmap.
// // // 2. **Anatomical Correlation** (2-3 sentences): Correlate the high-activation regions with the detected lesions and their anatomical locations.
// // // 3. **Diagnostic Significance** (2-3 sentences): Explain the clinical significance of the attention pattern in the context of the findings.
// // // 4. **AI Model Confidence Assessment** (1-2 sentences): Comment on the reliability of the model's focus based on the heatmap distribution.

// // // Keep the total response concise (150-220 words). Use formal medical terminology.`;

// // //     // strip data URI prefix si présent
// // //     const imageData = gradcamBase64.replace(/^data:image\/[a-z]+;base64,/, "");

// // //     const response = await client.messages.create({
// // //       model: "claude-sonnet-4-20250514",
// // //       max_tokens: 512,
// // //       system: systemPrompt,
// // //       messages: [
// // //         {
// // //           role: "user",
// // //           content: [
// // //             {
// // //               type: "image",
// // //               source: {
// // //                 type: "base64",
// // //                 media_type: "image/jpeg",
// // //                 data: imageData,
// // //               },
// // //             },
// // //             {
// // //               type: "text",
// // //               text: userPrompt,
// // //             },
// // //           ],
// // //         },
// // //       ],
// // //     });

// // //     const interpretation = response.content
// // //       .filter((b) => b.type === "text")
// // //       .map((b) => (b as any).text)
// // //       .join("");

// // //     return NextResponse.json({ interpretation });
// // //   } catch (err: any) {
// // //     console.error("Grad-CAM interpretation error:", err);
// // //     return NextResponse.json({ error: err.message ?? "Interpretation failed" }, { status: 500 });
// // //   }
// // // }


// // // app/api/ai/interpret-gradcam/route.ts
// // import { NextRequest, NextResponse } from "next/server";
// // import Anthropic from "@anthropic-ai/sdk";

// // const client = new Anthropic({
// //   apiKey: process.env.ANTHROPIC_API_KEY, // ← هذا اللي كان ناقص
// // });

// // export async function POST(req: NextRequest) {
// //   try {
// //     const body = await req.json();
// //     const {
// //       gradcamBase64,
// //       detections,
// //       analysisType,
// //       overallRisk,
// //       modelVersion,
// //     } = body;

// //     if (!gradcamBase64) {
// //       return NextResponse.json({ error: "No Grad-CAM image provided" }, { status: 400 });
// //     }

// //     const findingsSummary = detections?.length > 0
// //       ? detections.map((d: any) =>
// //           `- ${d.label} (Confidence: ${Math.round(d.confidence)}%, Severity: ${d.severity}, Location: ${d.location || "unspecified"})`
// //         ).join("\n")
// //       : "No pathological findings detected.";

// //     const systemPrompt = `You are an expert gastroenterologist and medical AI specialist. 
// // You are analyzing a Gradient-weighted Class Activation Map (Grad-CAM) heatmap generated by an AI model (${modelVersion}) during endoscopic image analysis.
// // Your role is to provide a professional, concise radiological interpretation of the activation map for inclusion in a formal medical report.
// // Write in clear, formal medical language suitable for a gastroenterology report.
// // Be specific about anatomical regions, activation patterns, and clinical significance.
// // Do NOT mention that this is AI-generated text. Write as a physician would write in a compte rendu.`;

// //     const userPrompt = `Analysis Context:
// // - Analysis type: ${analysisType === "detection" ? "Lesion Detection (Computer-Aided Detection)" : "Lesion Segmentation (Pixel-level Analysis)"}
// // - Overall risk assessment: ${overallRisk}
// // - AI Model: ${modelVersion}
// // - Detected findings:
// // ${findingsSummary}

// // The attached image is the Grad-CAM activation heatmap overlaid on the endoscopic image.
// // Hot regions (red/yellow) indicate areas of highest neural network attention during the classification decision.
// // Cold regions (blue/purple) indicate areas of low diagnostic relevance.

// // Please provide a structured medical interpretation with these sections:
// // 1. **Activation Pattern** (2-3 sentences): Describe the spatial distribution and intensity of activation zones observed in the heatmap.
// // 2. **Anatomical Correlation** (2-3 sentences): Correlate the high-activation regions with the detected lesions and their anatomical locations.
// // 3. **Diagnostic Significance** (2-3 sentences): Explain the clinical significance of the attention pattern in the context of the findings.
// // 4. **AI Model Confidence Assessment** (1-2 sentences): Comment on the reliability of the model's focus based on the heatmap distribution.

// // Keep the total response concise (150-220 words). Use formal medical terminology.`;

// //     const imageData = gradcamBase64.replace(/^data:image\/[a-z]+;base64,/, "");

// //     const response = await client.messages.create({
// //       model: "claude-sonnet-4-5", // ← موديل جديد
// //       max_tokens: 512,
// //       system: systemPrompt,
// //       messages: [
// //         {
// //           role: "user",
// //           content: [
// //             {
// //               type: "image",
// //               source: {
// //                 type: "base64",
// //                 media_type: "image/jpeg",
// //                 data: imageData,
// //               },
// //             },
// //             {
// //               type: "text",
// //               text: userPrompt,
// //             },
// //           ],
// //         },
// //       ],
// //     });

// //     const interpretation = response.content
// //       .filter((b) => b.type === "text")
// //       .map((b) => (b as any).text)
// //       .join("");

// //     return NextResponse.json({ interpretation });
// //   } catch (err: any) {
// //     console.error("Grad-CAM interpretation error:", err);
// //     return NextResponse.json({ error: err.message ?? "Interpretation failed" }, { status: 500 });
// //   }
// // }

// // app/api/ai/interpret-gradcam/route.ts
// import { NextRequest, NextResponse } from "next/server";
// import { GoogleGenerativeAI } from "@google/generative-ai";

// const client = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

// const model = client.getGenerativeModel(
//   { model: "gemini-2.5-flash-lite" },
//   { apiVersion: "v1" }   // ← هذا هو الحل
// );

// export async function POST(req: NextRequest) {
//   try {
//     const body = await req.json();
//     const {
//       gradcamBase64,
//       detections,
//       analysisType,
//       overallRisk,
//       modelVersion,
//     } = body;

//     if (!gradcamBase64) {
//       return NextResponse.json(
//         { error: "No Grad-CAM image provided" },
//         { status: 400 }
//       );
//     }

//     const findingsSummary =
//       detections?.length > 0
//         ? detections
//             .map(
//               (d: any) =>
//                 `- ${d.label} (Confidence: ${Math.round(d.confidence)}%, Severity: ${d.severity}, Location: ${d.location || "unspecified"})`
//             )
//             .join("\n")
//         : "No pathological findings detected.";

//     const fullPrompt = `You are an expert gastroenterologist and medical AI specialist.
// You are analyzing a Gradient-weighted Class Activation Map (Grad-CAM) heatmap generated by an AI model (${modelVersion}) during endoscopic image analysis.
// Your role is to provide a professional, concise radiological interpretation of the activation map for inclusion in a formal medical report.
// Write in clear, formal medical language suitable for a gastroenterology report.
// Be specific about anatomical regions, activation patterns, and clinical significance.
// Do NOT mention that this is AI-generated text. Write as a physician would write in a compte rendu.

// Analysis Context:
// - Analysis type: ${analysisType === "detection" ? "Lesion Detection (Computer-Aided Detection)" : "Lesion Segmentation (Pixel-level Analysis)"}
// - Overall risk assessment: ${overallRisk}
// - AI Model: ${modelVersion}
// - Detected findings:
// ${findingsSummary}

// The attached image is the Grad-CAM activation heatmap overlaid on the endoscopic image.
// Hot regions (red/yellow) indicate areas of highest neural network attention during the classification decision.
// Cold regions (blue/purple) indicate areas of low diagnostic relevance.

// Please provide a structured medical interpretation with these sections:
// 1. **Activation Pattern** (2-3 sentences): Describe the spatial distribution and intensity of activation zones observed in the heatmap.
// 2. **Anatomical Correlation** (2-3 sentences): Correlate the high-activation regions with the detected lesions and their anatomical locations.
// 3. **Diagnostic Significance** (2-3 sentences): Explain the clinical significance of the attention pattern in the context of the findings.
// 4. **AI Model Confidence Assessment** (1-2 sentences): Comment on the reliability of the model's focus based on the heatmap distribution.

// Keep the total response concise (150-220 words). Use formal medical terminology.`;

//     // strip data URI prefix
//     const imageData = gradcamBase64.replace(/^data:image\/[a-z]+;base64,/, "");

//     const model = client.getGenerativeModel({
//       model: "gemini-2.5-flash-lite",
//     });

//     // const result = await model.generateContent([
//     //   fullPrompt,
//     //   {
//     //     inlineData: {
//     //       mimeType: "image/jpeg",
//     //       data: imageData,
//     //     },
//     //   },
//     // ]);

//     async function generateWithRetry(model: any, parts: any[], maxRetries = 3) {
//   for (let i = 0; i < maxRetries; i++) {
//     try {
//       return await model.generateContent(parts);
//     } catch (err: any) {
//       if (err?.status === 429 && i < maxRetries - 1) {
//         const delay = (i + 1) * 7000; // 7s, 14s, 21s
//         await new Promise(r => setTimeout(r, delay));
//         continue;
//       }
//       throw err;
//     }
//   }
// }

// const result = await generateWithRetry(model, [
//   fullPrompt,
//   { inlineData: { mimeType: "image/jpeg", data: imageData } },
// ]);

//     const interpretation = result.response.text();

//     return NextResponse.json({ interpretation });
//   } catch (err: any) {
//     console.error("Grad-CAM interpretation error:", err);
//     return NextResponse.json(
//       { error: err.message ?? "Interpretation failed" },
//       { status: 500 }
//     );
//   }
// }

import { NextRequest, NextResponse } from "next/server";
import Groq from "groq-sdk";

const client = new Groq({ apiKey: process.env.GROQ_API_KEY! });

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { gradcamBase64, detections, analysisType, overallRisk, modelVersion } = body;

    if (!gradcamBase64) {
      return NextResponse.json({ error: "No Grad-CAM image provided" }, { status: 400 });
    }

    const findingsSummary = detections?.length > 0
      ? detections.map((d: any) =>
          `- ${d.label} (Confidence: ${Math.round(d.confidence)}%, Severity: ${d.severity}, Location: ${d.location || "unspecified"})`
        ).join("\n")
      : "No pathological findings detected.";

    const imageData = gradcamBase64.replace(/^data:image\/[a-z]+;base64,/, "");

    // نبني سياق النتائج التفصيلي
    const hasDetections = detections?.length > 0;
    const primaryDetection = detections?.[0];
    const detectionContext = hasDetections
      ? `The AI model classified this frame as POSITIVE for ${primaryDetection?.label ?? "polyp"} with ${Math.round(primaryDetection?.confidence ?? 0)}% confidence (severity: ${primaryDetection?.severity ?? "unspecified"}).`
      : "The AI model found no significant lesion in this frame.";

    const response = await client.chat.completions.create({
      model: "meta-llama/llama-4-scout-17b-16e-instruct",
      max_tokens: 800,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${imageData}`,
              },
            },
            {
              type: "text",
              text: `You are a senior gastroenterologist reviewing an endoscopic image with an AI activation map overlay.

WHAT YOU ARE LOOKING AT:
This image is a GradCAM heatmap superimposed on the original endoscopic frame.
- WARM zones (red, orange, yellow): the exact regions where the AI model concentrated its attention to conclude that a POLYP is present.
- COOL zones (blue, dark): mucosal areas the model considered irrelevant to the diagnosis.

AI DECISION:
${detectionContext}
Overall risk: ${overallRisk}
Model: ${modelVersion}
${hasDetections ? `All findings:\n${findingsSummary}` : ""}

YOUR TASK:
Examine the WARM (red/orange/yellow) regions carefully. In those highlighted areas, describe the specific endoscopic mucosal features that are consistent with a polyp: elevation above surrounding mucosa, surface texture (smooth, lobulated, irregular), pit pattern, abnormal vascular architecture, color difference from background mucosa, and morphological type (sessile, pedunculated, flat — Paris classification if applicable).

Write a clinical interpretation (3 to 4 sentences) explaining WHY the model focused on that particular zone, by describing the visible lesion characteristics present there. Your text will appear in the Grad-CAM Interpretation section of a formal endoscopy report.

STRICT FORMAT RULES:
- Plain text only. No asterisks, no bullet points, no markdown, no bold.
- Do NOT say "the heatmap shows" or "the red region" or "the AI focused". Instead say "the highlighted zone demonstrates..." or "the area of maximal activation corresponds to..."
- Do NOT render a histological diagnosis. Use hedging: "consistent with", "suggestive of", "morphologically compatible with".
- 80 to 120 words maximum.`
            },
          ],
        },
      ],
    });

    const interpretation = response.choices[0]?.message?.content ?? null;
    return NextResponse.json({ interpretation });

  } catch (err: any) {
    console.error("Grad-CAM interpretation error:", err);
    return NextResponse.json({ error: err.message ?? "Interpretation failed" }, { status: 500 });
  }
}